---
abstract: 'A Connect Four game in ANSI'
author: []
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Games-ConnectFour
provides:
  Games::ConnectFour:
    file: lib/Games/ConnectFour.pm
    version: 0.012
recommends:
  Test::Pod: 1.22
  Test::Pod::Coverage: 0.18
requires:
  File::ShareDir: 1.00
  Test::More: 0
  Win32::Console::ANSI: 1.04
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Blaizer/ConnectFour
version: 0.012
